apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: react-app-ingress
  labels:
    app: react-app
spec:
  ingressClassName: {{.Values.ingress.className}}
  rules:
    - host: {{.Values.ingress.host}}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: react-app-service
                port:
                  number: {{.Values.service.port}}
