apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: react-app-application
  namespace: react-app
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/stlee321/gitops-with-argocd.git
    targetRevision: HEAD
    path: reactapp
  destination:
    server: https://kubernetes.default.svc
    namespace: react-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
