name: build react app Image and push to container registry
on:
  workflow_dispatch:
  push:
    branches:
      - release
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: react-app
permissions:
  contents: read
  packages: write
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./react-app
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: set up nodejs 18
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: clean install dependencies
        run: npm ci
      - name: build react app
        run: npm run build
      - name: get metadata of image
        id: meta
        uses: docker/metadata-action@v5
        with:
          image: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          type: sha
      - name: login to Github Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: push to container registry
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.lables }}
